namespace MuetongWeb.Constants
{
    public static class SequenceConstants
    {
        public static string PoNoBuilder(int year, int month, short seq)
        {
            year -= 2000;if (year > 100) year -= 500;
            return string.Format("PO{0:00}{1:00}-{2:000}", year, month, seq);
        }
        public static string GetPoNoByMonth(int m)
        {
            string seqName = "Po" + m.ToString();
            return string.Format("SELECT NEXT VALUE FOR {0};SELECT @returnValue = CONVERT(smallint, current_value) FROM sys.sequences WHERE [name] = '{0}';", seqName);
        }
        public static List<string> ResetSequence = new List<string>() {
            @"ALTER SEQUENCE Po2 RESTART;ALTER SEQUENCE Po3 RESTART;
            ALTER SEQUENCE Po4 RESTART; ALTER SEQUENCE Po5 RESTART; ALTER SEQUENCE Po6 RESTART;
            ALTER SEQUENCE Po7 RESTART; ALTER SEQUENCE Po8 RESTART; ALTER SEQUENCE Po9 RESTART;
            ALTER SEQUENCE Po10 RESTART; ALTER SEQUENCE Po11 RESTART; ALTER SEQUENCE Po12 RESTART;",

            @"ALTER SEQUENCE Po1 RESTART;ALTER SEQUENCE Po3 RESTART;
            ALTER SEQUENCE Po4 RESTART; ALTER SEQUENCE Po5 RESTART; ALTER SEQUENCE Po6 RESTART;
            ALTER SEQUENCE Po7 RESTART; ALTER SEQUENCE Po8 RESTART; ALTER SEQUENCE Po9 RESTART;
            ALTER SEQUENCE Po10 RESTART; ALTER SEQUENCE Po11 RESTART; ALTER SEQUENCE Po12 RESTART;",

            @"ALTER SEQUENCE Po1 RESTART;ALTER SEQUENCE Po2 RESTART;
            ALTER SEQUENCE Po4 RESTART; ALTER SEQUENCE Po5 RESTART; ALTER SEQUENCE Po6 RESTART;
            ALTER SEQUENCE Po7 RESTART; ALTER SEQUENCE Po8 RESTART; ALTER SEQUENCE Po9 RESTART;
            ALTER SEQUENCE Po10 RESTART; ALTER SEQUENCE Po11 RESTART; ALTER SEQUENCE Po12 RESTART;",

            @"ALTER SEQUENCE Po1 RESTART;ALTER SEQUENCE Po2 RESTART;ALTER SEQUENCE Po3 RESTART;
            ALTER SEQUENCE Po5 RESTART; ALTER SEQUENCE Po6 RESTART;
            ALTER SEQUENCE Po7 RESTART; ALTER SEQUENCE Po8 RESTART; ALTER SEQUENCE Po9 RESTART;
            ALTER SEQUENCE Po10 RESTART; ALTER SEQUENCE Po11 RESTART; ALTER SEQUENCE Po12 RESTART;",

            @"ALTER SEQUENCE Po1 RESTART;ALTER SEQUENCE Po2 RESTART;ALTER SEQUENCE Po3 RESTART;
            ALTER SEQUENCE Po4 RESTART; ALTER SEQUENCE Po6 RESTART;
            ALTER SEQUENCE Po7 RESTART; ALTER SEQUENCE Po8 RESTART; ALTER SEQUENCE Po9 RESTART;
            ALTER SEQUENCE Po10 RESTART; ALTER SEQUENCE Po11 RESTART; ALTER SEQUENCE Po12 RESTART;",

            @"ALTER SEQUENCE Po1 RESTART;ALTER SEQUENCE Po2 RESTART;ALTER SEQUENCE Po3 RESTART;
            ALTER SEQUENCE Po4 RESTART; ALTER SEQUENCE Po5 RESTART; 
            ALTER SEQUENCE Po7 RESTART; ALTER SEQUENCE Po8 RESTART; ALTER SEQUENCE Po9 RESTART;
            ALTER SEQUENCE Po10 RESTART; ALTER SEQUENCE Po11 RESTART; ALTER SEQUENCE Po12 RESTART;",

            @"ALTER SEQUENCE Po1 RESTART;ALTER SEQUENCE Po2 RESTART;ALTER SEQUENCE Po3 RESTART;
            ALTER SEQUENCE Po4 RESTART; ALTER SEQUENCE Po5 RESTART; ALTER SEQUENCE Po6 RESTART;
            ALTER SEQUENCE Po8 RESTART; ALTER SEQUENCE Po9 RESTART;
            ALTER SEQUENCE Po10 RESTART; ALTER SEQUENCE Po11 RESTART; ALTER SEQUENCE Po12 RESTART;",

            @"ALTER SEQUENCE Po1 RESTART;ALTER SEQUENCE Po2 RESTART;ALTER SEQUENCE Po3 RESTART;
            ALTER SEQUENCE Po4 RESTART; ALTER SEQUENCE Po5 RESTART; ALTER SEQUENCE Po6 RESTART;
            ALTER SEQUENCE Po7 RESTART; ALTER SEQUENCE Po9 RESTART;
            ALTER SEQUENCE Po10 RESTART; ALTER SEQUENCE Po11 RESTART; ALTER SEQUENCE Po12 RESTART;",

            @"ALTER SEQUENCE Po1 RESTART;ALTER SEQUENCE Po2 RESTART;ALTER SEQUENCE Po3 RESTART;
            ALTER SEQUENCE Po4 RESTART; ALTER SEQUENCE Po5 RESTART; ALTER SEQUENCE Po6 RESTART;
            ALTER SEQUENCE Po7 RESTART; ALTER SEQUENCE Po8 RESTART;
            ALTER SEQUENCE Po10 RESTART; ALTER SEQUENCE Po11 RESTART; ALTER SEQUENCE Po12 RESTART;",

            @"ALTER SEQUENCE Po1 RESTART;ALTER SEQUENCE Po2 RESTART;ALTER SEQUENCE Po3 RESTART;
            ALTER SEQUENCE Po4 RESTART; ALTER SEQUENCE Po5 RESTART; ALTER SEQUENCE Po6 RESTART;
            ALTER SEQUENCE Po7 RESTART; ALTER SEQUENCE Po8 RESTART; ALTER SEQUENCE Po9 RESTART;
            ALTER SEQUENCE Po11 RESTART; ALTER SEQUENCE Po12 RESTART;",

            @"ALTER SEQUENCE Po1 RESTART;ALTER SEQUENCE Po2 RESTART;ALTER SEQUENCE Po3 RESTART;
            ALTER SEQUENCE Po4 RESTART; ALTER SEQUENCE Po5 RESTART; ALTER SEQUENCE Po6 RESTART;
            ALTER SEQUENCE Po7 RESTART; ALTER SEQUENCE Po8 RESTART; ALTER SEQUENCE Po9 RESTART;
            ALTER SEQUENCE Po10 RESTART; ALTER SEQUENCE Po12 RESTART;",

            @"ALTER SEQUENCE Po1 RESTART;ALTER SEQUENCE Po2 RESTART;ALTER SEQUENCE Po3 RESTART;
            ALTER SEQUENCE Po4 RESTART; ALTER SEQUENCE Po5 RESTART; ALTER SEQUENCE Po6 RESTART;
            ALTER SEQUENCE Po7 RESTART; ALTER SEQUENCE Po8 RESTART; ALTER SEQUENCE Po9 RESTART;
            ALTER SEQUENCE Po10 RESTART; ALTER SEQUENCE Po11 RESTART;",
        };
    }
}
